version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LIMIT=6